name: Health Monitoring

on:
  schedule:
    - cron: '*/15 * * * *' # Cada 15 minutos
  workflow_dispatch:

jobs:
  health-check:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    strategy:
      matrix:
        environment: [staging, production]
    steps:
      - name: Check API Gateway
        run: |
          response=$(curl -s -o /dev/null -w "%{http_code}" https://${{ matrix.environment }}-api.tudominio.com/health || echo "000")
          if [ "$response" != "200" ]; then
            echo "❌ API Gateway health check failed with status: $response"
            exit 1
          else
            echo "✅ API Gateway is healthy"
          fi

      - name: Check Frontend
        run: |
          response=$(curl -s -o /dev/null -w "%{http_code}" https://${{ matrix.environment }}.tudominio.com || echo "000")
          if [ "$response" != "200" ]; then
            echo "❌ Frontend health check failed with status: $response"
            exit 1
          else
            echo "✅ Frontend is healthy"
          fi

      - name: Notify on failure
        if: failure()
        uses: 8398a7/action-slack@v3
        with:
          status: failure
          text: "🚨 Health check failed for ${{ matrix.environment }} environment"
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}

  # Performance monitoring
  performance-test:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
      
      - name: Run load tests
        run: |
          # Ejemplo con k6
          docker run --rm -v $PWD:/app grafana/k6 run /app/tests/load-test.js
      
      - name: Upload results
        uses: actions/upload-artifact@v4
        with:
          name: performance-results
          path: performance-results.json
